PATHPWD=.
# PATHBIN=$(PATHPWD)/bin  # 本来需要同时生成可执行文件和库，后来单独只生成库，就吧这行注释掉了
PATHLIB=$(PATHPWD)/lib
PATHSRC=$(PATHPWD)/src
PATHOBJ=$(PATHPWD)/obj


clean:
        echo $(PATHBIN)/* $(PATHBIN)/* $(PATHOBJ)/*

# 在编译服务器上执行make clean 以后可以跑路了